# Setup
title: kyre0e的博客
description: 简单的记录学习记录的个人博客网站
url: https://Kyre0ee.github.io
# Specify the author for blog posts
author:
  name: Kyre0e
  email: kyre0@outlook.com
  avatar: /avatar.jpeg
  
paginate: 5
permalink: pretty
cover_image: /bg.jpeg

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - .gemspec
  #- kyre0e.github.io.gemspec
  #- _posts/2020-09-29-welcome-to-not-pure-poole.md
  #- _posts/2020-10-01-releasing-not-pure-poole-v0-1-0.md
  #- _posts/2020-10-02-testing-mathjax.md
# Optimize Jekyl SEO Tag
#twitter:
#  username: kyre0e
#  card: summary
logo: logo.png
social:
  name: Kyre0ee
  links:
    #- https://twitter.com/kyre0e
    - https://github.com/Kyre0ee
google_site_verification: xxxxx
lang: zh

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

